jenkins:
  agentProtocols:
  - "Diagnostic-Ping"
  - "JNLP4-connect"
  - "OperationsCenter2"
  - "Ping"
credentials:
  system:
    - usernamePassword:
      scope: GLOBAL
      id: github-beedemo-ops
      username: beedemo-ops
      password: ${github-ops-token}
kube:
  podTemplatesConfiguration:
    templates:
      - name: maven2
        label: maven2podtemplate
        containers:
          - name: maven
            image: maven:3.3.9-jdk-8-alpine
            ttyEnabled: true
            command: cat
            args: ""
